server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bachstage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lzm57913
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    # 打印com.seecen.myjd.dao包下的sql语句日志
    com.example.market.dao: debug
